### ISSUE TITLE
Execution History Not Showing

### ISSUE THREAD

**Issue by ChestoOfGlen** [Shuffle/Shuffle#1256]
**Describe the bug**
Execution history is not displaying in the Shuffle web UI after upgrade to the latest tag (as of 9 November).
However workflows are executing because I can find the history the the "workflowexecution" index in Opensearch and see the results of the workflow having run in our case management platform.

It seems to be only for workflows that include a subflow, as other workflows that do not include a subflow show their execution history.

This was working fine while we were running on v1.2.0.

Here is a test workflow I created. When I manually execute the workflow I get the execution history, but as soon as I close the history of that execution and go back to the main list I am unable to see anything in the history.
![image](https://github.com/Shuffle/Shuffle/assets/37160206/6946a54d-d3d3-449b-963b-690fba9a33cc)
![image](https://github.com/Shuffle/Shuffle/assets/37160206/d1891fce-09a3-43f1-b688-dc974f7a9a4d)

**Comment by frikky** [comment]
> **Describe the bug** Execution history is not displaying in the Shuffle web UI after upgrade to the latest tag (as of 9 November). However workflows are executing because I can find the history the the "workflowexecution" index in Opensearch and see the results of the workflow having run in our case management platform.
> 
> It seems to be only for workflows that include a subflow, as other workflows that do not include a subflow show their execution history.
> 
> This was working fine while we were running on v1.2.0.
> 
> Here is a test workflow I created. When I manually execute the workflow I get the execution history, but as soon as I close the history of that execution and go back to the main list I am unable to see anything in the history. ![image](https://user-images.githubusercontent.com/37160206/281610352-6946a54d-d3d3-449b-963b-690fba9a33cc.png) ![image](https://user-images.githubusercontent.com/37160206/281610370-d1891fce-09a3-43f1-b688-dc974f7a9a4d.png)

Hey! 

This is a known issue and is due to a missconfigured /api/v2 nginx configuration in certain environments. We intend to have a fix released tonight for it on 1.3.0 and latest :)

**Comment by jmcparland** [comment]
My first encounters with my first, fresh, vanilla docker compose install: following youtube videos trying to get a webhook-to-repeat workflow to work, not seeing history. I tried changing it up to use a schedule trigger instead -- same issue: no run history (in the UI at least). Nothing found in the issues here (at least under "triggers" or "webhooks" or a broader search on discord). I thought I was losing my mind :-p  I was just about to start gathering the evidence for a discord post when I checked the docker logs indicating things were happening. Glad y'all are on it :-) // The install script / my currently failing env here has me pulling the nightly versions of shuffle-frontend, -backend, and -orborus with opensearch pinned at 2.11.0. (git commit a19b6ba)

**Comment by jmcparland** [comment]
Additional information. git checkout 1.3.0, adjusted docker-compose.yml for 1.3.0 for -frontend, -backend, -orborus & pulled, restarted.

- When accessing via https://url:3443, the problem persists.
- When accessing via http://url:3001, the error is gone.

The error in the browser when hitting "refresh runs" in the UI:

![image](https://github.com/Shuffle/Shuffle/assets/29742876/939c4609-ac7b-40ce-9f51-08c91a2ec4a5)

The sha1sum of nginx.conf inside the -frontend container I'm examining right now:

```bash
root@shuffle-frontend:/etc/nginx# sha1sum nginx.conf 
a6455555644835dbc87d4b2f7b07c0aba8612cb5  nginx.conf
```

**Comment by frikky** [comment]
Thanks for all the info! Just to make sure digging into this won't be a problem, and to further help debugging, we built a debugging window as well that will make it even easier to deal with executions :) 

<img width="959" alt="image" src="https://github.com/Shuffle/Shuffle/assets/5719530/576ca558-79ad-462e-908c-1c63a65cae3f">

**Comment by ChestoOfGlen** [comment]
Hey @frikky just confirming I've just bumped our frontend up to 1.3.0 just now, and I can view all execution histories again.

Just to note for anyone else who might find this issue ticket with the same issue, I also had to clear out my cookies/cache for our Shuffle instance.
Just doing the container update and a CTRL+F5 force refresh in Firefox didn't seem to be enough on its own to restore full function.

**Comment by jmcparland** [comment]
I appreciate that @ChestoOfGlen 's issue is cleared when updating to v1.3 -- very cool :-)  I'm still noting that the http and https handling is different -- that is, the issue was only corrected for http (at least in the current docker builds). Should we tee off as a separate issue? (Apologies -- I just haven't had a chance to circle back and dig in yet.)

### Current Situation

The following two screenshots are of the same workflow run history screen. Each uses a fresh firefox private browsing window so cookies are not an issue. Both are to the same service at v1.3 described earlier in the thread.  One access is via http (run history visible); the other https (run history *not* visible).

Here is the **http** view of a workflow's run history:

![http-run-history](https://github.com/Shuffle/Shuffle/assets/29742876/acb2962d-f0ca-4015-880b-981075d030af)

Here is the **https** view of the same run history:

![https-run-history](https://github.com/Shuffle/Shuffle/assets/29742876/5010af46-36ab-4325-9a55-0c6099c4a970)

**Comment by ChestoOfGlen** [comment]
I should also note that we are using HTTPS, not HTTP, in our setup and execution history is visible for us again (as above) after update to the most recent 1.3.0/latest container image for frontend (not that I have only updated the frontend at this stage).

HTTPS to Reverse Proxy > Reverse Proxy HTTPS on 8443 to Shuffle Frontend

**Comment by jmcparland** [comment]
Curious... For my results, I'm hitting it directly (vm on the lan running the docker-compose install with latest v1.3 -fe & -be), http to port 3001 and https to 3443.

Separately I have nginx on a public ip terminating https and reverse-proxying back to the 3001 port -- as expected, no issue there.

Anyway, no big deal -- my work's not blocked anymore :-)  I'll look at this some more later and let y'all know if I see anything.

Thanks @ChestoOfGlen & @frikky !

**Comment by jmcparland** [comment]
Going into the running front-end container and making the following adjustment to the `/etc/nginx/nginx.conf` file (https server block), it looks like all is well. (It's just a dup of the location line changed in the http server block.)

```
		# Get the hostname from environment here?
		# location /api/v1 {
		location ~ /api/v(1|2) {
```

I haven't checked the repo yet to see if the change is in there. If so, I may have just pulled a build where it wasn't there yet -- who knows? Anyway, that clears it up -- run history loads for both http & https now  :-)
