### ISSUE TITLE
Shuffle workflow is in executing state

### ISSUE THREAD

**Issue by anjanaradhakrishnan** [Shuffle/Shuffle#1435]
Hello @frikky 
I have integrated the wazuh with shuffle. Also we have integrated the thehive with shuffle for case creation.
So whenever an alert comes wazuh webhook will trigger the workflow  and based the condition it will create a case in thehive .
The issue am facing here is the workflow is in executing state. It is not completing .  Its been 1 day and the state is still executing.

<img width="233" alt="image" src="https://github.com/Shuffle/Shuffle/assets/105666732/a41788d8-5f4d-4918-8ef6-7a0b518f0f2f">

There are pods created for the worker and thehive for shuffle after each executions

<img width="481" alt="image" src="https://github.com/Shuffle/Shuffle/assets/105666732/489617dd-32f6-4a9e-af4e-8086887b428c">

Need your help on this @frikky

**Comment by frikky** [comment]
> Hello @frikky I have integrated the wazuh with shuffle. Also we have integrated the thehive with shuffle for case creation. So whenever an alert comes wazuh webhook will trigger the workflow and based the condition it will create a case in thehive . The issue am facing here is the workflow is in executing state. It is not completing . Its been 1 day and the state is still executing.
> 
> <img alt="image" width="233" src="https://private-user-images.githubusercontent.com/105666732/341949628-a41788d8-5f4d-4918-8ef6-7a0b518f0f2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwOTMwNDQsIm5iZiI6MTcxOTA5Mjc0NCwicGF0aCI6Ii8xMDU2NjY3MzIvMzQxOTQ5NjI4LWE0MTc4OGQ4LTVmNGQtNDkxOC04ZWY2LTdhMGI1MThmMGYyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMlQyMTQ1NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NzJiY2IxYTU2ZjllMmQwMjJlYTlkYmZkNGVjNjhhODlkYmQxNDNhMGUwMDEzZDE1ODdmZDc4ZGEzNzJmOWE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._xy31MFftt528xbAPNaH2oESdaZJHhp0JNhxhmeoouo">
> There are pods created for the worker and thehive for shuffle after each executions
> 
> <img alt="image" width="481" src="https://private-user-images.githubusercontent.com/105666732/341970988-489617dd-32f6-4a9e-af4e-8086887b428c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwOTMwNDQsIm5iZiI6MTcxOTA5Mjc0NCwicGF0aCI6Ii8xMDU2NjY3MzIvMzQxOTcwOTg4LTQ4OTYxN2RkLTMyZjYtNGE5ZS1hZjRlLTgwODY4ODdiNDI4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMlQyMTQ1NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZDE5Zjc2NzE5YWZhYzY4YmRhMDJkM2I4MzQ5N2Y3ZDAwOWYyY2ZmZTg4OGJlYjJiZGUzZjcxMDU5NzJmYjg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qd0Egnp3qUPSLuZXaQ1DNF7KmZ78vUePZn7P8GiP3i8">
> Need your help on this @frikky

The typical issue is that the correct images aren't available. My colleague @0x0elliot can help you out! Setting up a support call with them should resolve this for you :)

PS: It is not actually executing - it's just waiting for the app(s) to run, which they won't automatically do.

**Comment by 0x0elliot** [comment]
Hey! Let's talk here: https://cal.com/aditya-shuffle/30min

**Comment by Kagetana** [comment]
I might face same issue, @0x0elliot can u please describe steps to fix?

**Comment by Thibs-mgs012345** [comment]
Hi, I'm having the same issue too, workflows stuck in executing state, @0x0elliot can you please explain how to fix this ?

**Comment by frikky** [comment]
Hey everyone! As we put out a notice about about a month ago, there was an issue in apps created in the app creator, leading them to having code issues.

This is fixed in [1.4.2](https://github.com/Shuffle/Shuffle/releases) - please update to the latest version!

**Comment by Thibs-mgs012345** [comment]
Hi, I did a complete fresh install of the 1.4.2 release and the issue is still here.

**Comment by 0x0elliot** [comment]
@Thibs-mgs012345 delete the docker image of the app that's giving you this issue and try again. That is the solution :)

**Comment by Thibs-mgs012345** [comment]
@0x0elliot I Have this issue with all apps :( I did a complete removal of all docker images / volumes and networks, Then I cloned the Shuffle and Shuffle-apps repository, and finnaly edited the yml to get my proxy conf, but the issue is still here (worker are created but Workflows are still stuck in execution).

I'm on AlmaLinux release 8.10 (Cerulean Leopard).

Maybe the issue is about the system/configuration of my host, gonna try a fresh install on a VM and give a feedback.

Anyway, thanks for the help :)

**Comment by 0x0elliot** [comment]
book a call on my cal for tomorrow. let me see why it's not being fixed automatically.

**Comment by Thibs-mgs012345** [comment]
It's gonna ne tough for me tomorrow :/, is Wednesday's or later OK for you ? 

BTW here is the cal URL : https://cal.com/thibs-mgs012345/60min

**Comment by xyy-ws** [comment]
I have the same problem. It first happened when I create app with Openapi but it fixed when I upgraded to 1.4.1 . Then when I try to create app with python manually it happen again.

**Comment by Thibs-mgs012345** [comment]
> Hey! Let's talk here: https://cal.com/aditya-shuffle/30min

I didn't see you've alreaday shared a cal URL, I booked a call for Wednesday 2 PM

**Comment by Thibs-mgs012345** [comment]
Thanks @0x0elliot for this meeting, everything is working well now ! 

For those wondering, here is what I did :
- Delete all the Shuffle app's files
- Delete all docker related stuff : Image, volumes, networks ....
- Then clone the Shuffle and python-apps repositories
- Start the app with docker compose up

**Comment by frikky** [comment]
> Thanks @0x0elliot for this meeting, everything is working well now !
> 
> For those wondering, here is what I did :
> 
> * Delete all the Shuffle app's files
> * Delete all docker related stuff : Image, volumes, networks ....
> * Then clone the Shuffle and python-apps repositories
> * Start the app with docker compose up

The main thing here is that the App images need to be remade! Going into the apps you want and clicking "Save" on them will fix it.

**Comment by 0x0elliot** [comment]
@xyy-ws Do you also require some help? I don't mind taking about 15-20 minutes for your setup as well.
