### ISSUE TITLE
Orborus unable to pull app images for app updates and installs when on-prem

### ISSUE THREAD

**Issue by darksources** [Shuffle/Shuffle#1649]
**Describe the bug**
When Orborus is given a push request there appears to be a Golang syntax error causing artifact in the pull URL

**To Reproduce**
Update an app or install a new one.

**Expected behavior**
App to be pulled from the frontend and installed.

** Debug logs (NOT APPLICABLE FOR CLOUD)**
2025/03/11 11:32:15 [DEBUG] Downloading image as POST request WITHOUT redirects due to not being cloud
2025/03/11 11:32:15 [ERROR] Failed removing image: Error response from daemon: No such image: frikky/shuffle:iris_v2_562cf3f21fcc2f315c985a34aa23a001. Resp: []image.DeleteResponse(nil)
2025/03/11 11:32:15 [ERROR] Failed to create request for frikky/shuffle:iris_v2_1.1.0: parse "http://[host]:3001/api/v1/get_docker_image%!(EXTRA string=frikky/shuffle:iris_v2_1.1.0)": invalid URL escape "%!("

**Comment by darksources** [comment]
Installing orborus version 2.0.0-nightly-22012025-2 allows apps. While 2.0.0, latest, and nightly have the above issue.

**Comment by phoenixSpark** [comment]
Hi - thank you - that solved the issue!

**Comment by frikky** [comment]
Hey guys,

thanks for checking in on all this! The push system has been drastically updated (including manual sends), and it is indeed just a formatting error which has been corrected. 

The fix will go out to `latest` today.

**Comment by darksources** [comment]
Has this been pushed? As of today 3/20 I am still seeing the issue with both nightly an latest.
