### ISSUE TITLE
Nested variable referencing fails in UI if the complete variable is already referenced

### ISSUE THREAD

**Issue by yashsinghcodes** [Shuffle/Shuffle#1864]
When using a nested variable reference, it cannot be accessed in the UI if the complete variable has already been referenced earlier. Attached the relevant screenshot.

<img width="936" height="368" alt="Image" src="https://github.com/user-attachments/assets/54497ded-44f8-4c02-9614-ac46a7649158" />

**Comment by frikky** [comment]
wtf 😆 

@Monilprajapati can you fix this?

**Comment by Monilprajapati** [comment]
Sure

**Comment by Monilprajapati** [comment]
Fixed on the cloud.

Here is the sync PR for onPrem : https://github.com/Shuffle/Shuffle/pull/1865

**Comment by yashsinghcodes** [comment]
<img width="1036" height="445" alt="Image" src="https://github.com/user-attachments/assets/6d5a6483-ae2d-4d6f-a1eb-2a196365a4e9" />

Looks likes issue still exists in nightly and latest

**Comment by padel-0** [comment]
for your reference, I pulled the latest docker image tags today (2025-11-18 @ 14:15 UTC) for all shuffle components (frontend, backend, orborus and memcached) and still have this issue, but it seems to only be an UI bug  
the code block is executed as expected and works on this example

my example:

1. I have a "Repeat back to me" debugger node as startnode, with the following example data:

```json
{"id":101,"name":"Example Dataset","type":"root_object","timestamp":"2025-11-04T12:00:00Z","owner":{"name":"Test-User","department":"Security Operations","contact":{"email":"user@example.com","phone":"+43 664 1234567","address":{"street":"Musterstraße 42","city":"Wels","postal_code":"4200","country":"Austria"}}},"metadata":{"created_by":"system","last_modified":"2025-11-04T13:30:00Z","version":1.2}}
```

2. the next node in line is a "Repeat back to me" node as well, with the code block from the screenshot:

```py
{% python %}

import json

# access nested value before parent access
contact_email = "$debugger.owner.contact.email"

# load full parent object
full_owner = r"""$debugger.owner"""
jsondata = json.loads(full_owner)


# access nested value after parent access
contact_phone = "$debugger.owner.contact.phone"


print({
  "extracted_mail": contact_email,
  "extracted_phone": contact_phone,
  "full_owner": jsondata
})


{% endpython %}
```

behaviour is the same on an "Execute python" node, and as said, the code works as intended, only the "preview" pane of the code show the malformed code
